// Auto-generated by LibreLane
module cpu(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset,
  output halt,
  output[27:0] IC,
  input[15:0] instr,
  output[27:0] DataAddress,
  output[27:0] DataMemoryWrite,
  input[27:0] DataMemoryRead,
  output DmemReadEn,
  output DmemWriteEn
);
endmodule
