//! Combinational arithmetic logic unit for ISA v1 register operations, moves, shifts, and comparisons.
module alu #(
    //! Width of each ALU operand and result word.
    parameter DATA_WORD_WIDTH = 28,
    //! Width of the ALU operation selector.
    parameter CONTROL_OP_WIDTH = 4
) (
    //! Clock carried for module contract symmetry with the CPU datapath.
    input clk,
    //! Reset carried for module contract symmetry with the CPU datapath.
    input reset,
    //! Halt carried for module contract symmetry with the CPU datapath.
    input halt,
    //! First ALU operand, normally Ra data or MEMOFF during memory address calculation.
    input [DATA_WORD_WIDTH-1:0] OperandA,
    //! Second ALU operand, normally Rb/source data.
    input [DATA_WORD_WIDTH-1:0] OperandB,
    //! Operation selector generated by the controller.
    input [CONTROL_OP_WIDTH-1:0] ALUCtrl,
    //! Combinational result for the selected ALU operation.
    output reg [DATA_WORD_WIDTH-1:0] result,
    //! Equality flag asserted when OperandA equals OperandB.
    output reg zero,
    //! Unsigned less-than flag asserted when OperandA is below OperandB.
    output reg altb
);


    //TODO: Document this for the teroshdl documenter

    //! Operation code for bitwise inversion.
    localparam  ALU_NOT = 4'b0000;
    //! Operation code for bitwise OR.
    localparam  ALU_OR  = 4'b0001;
    //! Operation code for bitwise AND.
    localparam  ALU_AND = 4'b0010;
    //! Operation code for bitwise XOR.
    localparam  ALU_XOR = 4'b0011;
    //! Operation code for logical left shift.
    localparam  ALU_SHL = 4'b0100;
    //! Operation code for logical right shift.
    localparam  ALU_SHR = 4'b0101;
    //! Operation code for arithmetic right shift.
    localparam  ALU_SAR = 4'b0110;
    //! Operation code for addition.
    localparam  ALU_ADD = 4'b0111;
    //! Operation code for subtraction.
    localparam  ALU_SUB = 4'b1000;
    //! Operation code for MOV, forwarding OperandB.
    localparam  ALU_MOV = 4'b1001;


    //! Computes the selected ALU operation and updates comparison flags.
    always @(*) begin : operation_select
        case (ALUCtrl)
            //! Produces the bitwise inverse of OperandA.
            // TODO: Add another NOT method to use the hardware efficiently by inverting BOTH OpA and OpB
            ALU_NOT : begin
                result = ~OperandA;
            end 
            ALU_OR : begin
                result = OperandA | OperandB;
            end
            ALU_AND : begin
                result = OperandA & OperandB;
            end
            ALU_XOR : begin
                result = OperandA ^ OperandB;
            end
            ALU_SHL : begin
                result = OperandA << OperandB;
            end
            ALU_SHR : begin
                result = OperandA >> OperandB;
            end
            ALU_SAR : begin
                result = $signed(OperandA) >>> OperandB;
            end
            ALU_ADD : begin
                result = OperandA + OperandB;
            end
            ALU_SUB : begin
                result = OperandA - OperandB;
            end
            ALU_MOV : begin
                result = OperandB;
            end

            //! Default operation forwards OperandA.
            default:  result = OperandA;
        endcase

        zero = (OperandA == OperandB);
        altb = (OperandA < OperandB);
    end

endmodule
